
services:
###> doctrine/doctrine-bundle ###
  database:
    # Optimisations dev (NE PAS UTILISER EN PROD)
    command: postgres -c fsync=off -c synchronous_commit=off
    shm_size: 256mb
    tmpfs:
      - /var/run/postgresql
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
